### ISSUE TITLE
ALS hdf reader fail data load

### ISSUE THREAD

**Issue by decarlof** [data-exchange/dxchange#20]
proj, flat, dark = dxchange.read_als_832h5(fname)
fails on 

20150820_124324_Dleucopodia_10458_pieceA_10x_z80mm_moreangles.h5

Traceback (most recent call last):
  File "rec_als_hdf5.py", line 172, in <module>
    proj, flat, dark = dxchange.read_als_832h5(fname)
ValueError: too many values to unpack

**Comment by decarlof** [comment]
@lbluque I just tested your last pull request and it address this issue so I will close both

**Comment by decarlof** [comment]
@lbluque ops I take it back when importing a large ALS data set I still get:

fname = '20150820_124324_Dleucopodia_10458_pieceA_10x_z80mm_moreangles.h5'
proj, flat, dark = dxchange.read_als_832h5(fname)
Traceback (most recent call last):
  File "rec_als_hdf5.py", line 172, in <module>
    proj, flat, dark = dxchange.read_als_832h5(fname)
ValueError: too many values to unpack

**Comment by decarlof** [comment]
solved at https://github.com/data-exchange/dxchange/commit/e4f8f3e4d018b80776d12b83ad44b292cae4c5a7
